#!/bin/bash
# Deployment preparation script

echo "Preparing for production deployment..."

# Create a deployment configuration file that will be used during the build
cat > deployment-config.js << EOF
// This file is automatically generated during deployment
// It contains optimized build settings for production

export const DEPLOYMENT_CONFIG = {
  // Force production mode
  NODE_ENV: 'production',
  
  // Optimize build flags
  BUILD_OPTIMIZATION: {
    minify: true,
    treeshake: true,
    splitChunks: true,
    compress: true
  },
  
  // Ensure session security in production
  SESSION_CONFIG: {
    secure: true,
    httpOnly: true,
    sameSite: 'strict'
  }
};
EOF

echo "Deployment configuration prepared."
echo "When deploying, ensure environment variables are properly set in Replit Secrets."
echo "Required variables for production:"
echo "- DATABASE_URL"
echo "- GOOGLE_CLIENT_ID"
echo "- GOOGLE_CLIENT_SECRET"
echo "- PRODUCTION_DOMAIN"
echo "- SESSION_SECRET"
echo "- BASE_RPC_API_KEY"

echo "Deployment preparation complete!"